wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.6
    start_time: 1630427883
    t:
      1:
      - 1
      2:
      - 1
      3:
      - 1
      4: 3.9.6
      5: 0.12.0
      8:
      - 3
      - 5
log_interval:
  desc: null
  value: 100
no_cuda:
  desc: null
  value: false
seed:
  desc: null
  value: 42
