wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.33
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.8
    t:
      1:
      - 1
      4: 3.6.8
      5: 0.10.33
      8:
      - 5
log_interval:
  desc: null
  value: 100
no_cuda:
  desc: null
  value: false
seed:
  desc: null
  value: 42
